### PR TITLE
Update to LLVM 14 (C++17 support)

### PR DESCRIPTION
**Pull request by andreittr**
Update libcxx to 14.0.6.
This is part of a patch set consisting of:
 - [libcxx](https://github.com/unikraft/lib-libcxx/pull/28)
 - [libcxxabi](https://github.com/unikraft/lib-libcxxabi/pull/4)
 - [lib-compiler-rt](https://github.com/unikraft/lib-compiler-rt/pull/12)
 - [libunwind](https://github.com/unikraft/lib-libunwind/pull/7)
 - [musl](https://github.com/unikraft/lib-musl/pull/45)
 - [unikraft/build](https://github.com/unikraft/unikraft/pull/881)

Tested with GCC 11, 12 & 13, and clang 16.

edit: add compiler-specific warnings from @mschlumpp

### CODE REVIEW

**Comment by StefanJum** [comment]
@andreittr I get the following issue, building `app-helloworld-cpp` with the prs that you mentioned:
```
In file included from workdir/apps/app-helloworld-cpp/build/libunwind/origin/libunwind-14.0.6.src/src/UnwindRegistersRestore.S:9:
workdir/apps/app-helloworld-cpp/build/libunwind/origin/libunwind-14.0.6.src/src/assembly.h:19:10: fatal error: cet.h: No such file or directory
   19 | #include <cet.h>
```

gcc version `gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0`

libs in the `Makefile`: `LIBS := $(UK_LIBS)/libcxxabi:$(UK_LIBS)/libcxx:$(UK_LIBS)/compiler-rt:$(UK_LIBS)/libunwind:$(UK_LIBS)/musl`

Looks like [`__CET__`](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcf-protection) gets defined somewhere, I don't know where or why, the `-fcf-protection` flag does not seem to be used anywhere.

**Comment by andreittr** [comment]
> Looks like [__CET__](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcf-protection) gets defined somewhere, I don't know where or why, the -fcf-protection flag does not seem to be used anywhere.

Any chance `-fcf-protection` is a default flag on your system's compiler? (`cc -E -dM - < /dev/null | grep CET`)
If so, you might not be the only one and we need to explicitly add `-fcf-protection=none` to CFLAGS (universally, as different cf-protection settings across compilation units might/will error out at link time)

OTOH supporting control-flow protection in general is a very good idea for security, but since `cet.h` is a compiler header rather than a library header, this brings us back to the issue of cleanly pulling only the compiler headers into the unikaft build for stuff like this and intrinsics and whatnot.

**Comment by StefanJum** [comment]
> > Looks like [**CET**](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fcf-protection) gets defined somewhere, I don't know where or why, the -fcf-protection flag does not seem to be used anywhere.
> 
> Any chance `-fcf-protection` is a default flag on your system's compiler? (`cc -E -dM - < /dev/null | grep CET`) If so, you might not be the only one and we need to explicitly add `-fcf-protection=none` to CFLAGS (universally, as different cf-protection settings across compilation units might/will error out at link time)

Yes, that's it: `#define __CET__ 3`.

**Comment by andreittr** [comment]
> Yes, that's it: #define __CET__ 3.

Thanks, I'll cook up a change to the main unikraft repo adding the req'd CFLAGS; new PR coming soon to this patch set.

edit: done, see link in PR description

**Review by StefanJum — APPROVED** [review]
All good, thanks. Needs [unikraft/913](https://github.com/unikraft/unikraft/pull/913) to be integrated for it to work on `arm64` + `clang`.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
Thank you @andreittr for your patience and good work!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by eduardvintila — CHANGES_REQUESTED** [review]
Great work, @andreittr.

 I have only one small suggestion: I would also drop the `include/support/musl/math.h` file altogether, since in this PR you've removed the only [patch](https://github.com/unikraft/lib-libcxx/blob/staging/patches/0010-Use-libcxx-math-header-file-when-building-with-musl.patch) which was using it.

**Comment by andreittr** [comment]
@eduardvintila done. I've integrated that file's removal into the update commit (where all other unnecessary files are deleted).

**Review by razvand — APPROVED** [review]
I tested this as well, and it works as expected. Thanks, @andreittr.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

**Review by eduardvintila — APPROVED** [review]
Thanks, everyone!

Approved-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Pull request closed without merging**
